config/routes.rb
Associacao::Application.routes.draw do
  resources :ocorrencia

  resources :atendentes

  resources :seguros

  resources :automovels

  resources :clientes

end

app/models/atendente.rb
class Atendente < ActiveRecord::Base
end

app/models/automovel.rb
class Automovel < ActiveRecord::Base
  belongs_to :cliente
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/ocorrencium.rb
class Ocorrencium < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :seguro
  belongs_to :automovel
end

app/models/seguro.rb
class Seguro < ActiveRecord::Base
  belongs_to :automovel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/atendentes_controller.rb
class AtendentesController < InheritedResources::Base
end

app/controllers/automovels_controller.rb
class AutomovelsController < InheritedResources::Base
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
end

app/controllers/ocorrencia_controller.rb
class OcorrenciaController < InheritedResources::Base
end

app/controllers/seguros_controller.rb
class SegurosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendentes_helper.rb
module AtendentesHelper
end

app/helpers/automovels_helper.rb
module AutomovelsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/ocorrencia_helper.rb
module OcorrenciaHelper
end

app/helpers/seguros_helper.rb
module SegurosHelper
end

app/views/atendentes/_form.html.erb
<%= form_for(@atendente) do |f| %>
  <% if @atendente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atendente.errors.count, "error") %> prohibited this atendente from being saved:</h2>

      <ul>
      <% @atendente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atendentes/edit.html.erb
<h1>Editing atendente</h1>

<%= render 'form' %>

<%= link_to 'Show', @atendente %> |
<%= link_to 'Back', atendentes_path %>

app/views/atendentes/index.html.erb
<h1>Listing atendentes</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nome</th>
    <th>Cpf</th>
    <th>Rg</th>
    <th>Endereco</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @atendentes.each do |atendente| %>
  <tr>
    <td><%= atendente.codigo %></td>
    <td><%= atendente.nome %></td>
    <td><%= atendente.cpf %></td>
    <td><%= atendente.rg %></td>
    <td><%= atendente.endereco %></td>
    <td><%= link_to 'Show', atendente %></td>
    <td><%= link_to 'Edit', edit_atendente_path(atendente) %></td>
    <td><%= link_to 'Excluir', atendente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Atendente', new_atendente_path %>

app/views/atendentes/new.html.erb
<h1>New atendente</h1>

<%= render 'form' %>

<%= link_to 'Back', atendentes_path %>

app/views/atendentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @atendente.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%= @atendente.nome %>
</p>

<p>
  <b>Cpf:</b>
  <%= @atendente.cpf %>
</p>

<p>
  <b>Rg:</b>
  <%= @atendente.rg %>
</p>

<p>
  <b>Endereco:</b>
  <%= @atendente.endereco %>
</p>


<%= link_to 'Edit', edit_atendente_path(@atendente) %> |
<%= link_to 'Back', atendentes_path %>

app/views/automovels/_form.html.haml
= semantic_form_for(@automovel) do |f|
	= f.input :codigo, :label => 'codigo'
	= f.input :modelo, :label => 'modelo'
	= f.input :marca, :label => 'marca'
	= f.input :tipo, :label => 'tipo'
	= f.input :cliente, :member_label => :nome, :label => 'cliente'
	= f.submit 'Salvar'
  

app/views/automovels/edit.html.erb
<h1>Editing automovel</h1>

<%= render 'form' %>

<%= link_to 'Show', @automovel %> |
<%= link_to 'Back', automovels_path %>

app/views/automovels/index.html.erb
<h1>Listing automovels</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Modelo</th>
    <th>Marca</th>
    <th>Tipo</th>
    <th>Cliente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @automovels.each do |automovel| %>
  <tr>
    <td><%= automovel.codigo %></td>
    <td><%= automovel.modelo %></td>
    <td><%= automovel.marca %></td>
    <td><%= automovel.tipo %></td>
    <td><%= automovel.cliente %></td>
    <td><%= link_to 'Show', automovel %></td>
    <td><%= link_to 'Edit', edit_automovel_path(automovel) %></td>
    <td><%= link_to 'Excluir', automovel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Automovel', new_automovel_path %>

app/views/automovels/new.html.erb
<h1>New automovel</h1>

<%= render 'form' %>

<%= link_to 'Back', automovels_path %>

app/views/automovels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @automovel.codigo %>
</p>

<p>
  <b>Modelo:</b>
  <%= @automovel.modelo %>
</p>

<p>
  <b>Marca:</b>
  <%= @automovel.marca %>
</p>

<p>
  <b>Tipo:</b>
  <%= @automovel.tipo %>
</p>

<p>
  <b>Cliente:</b>
  <%= @automovel.cliente.nome %>
</p>


<%= link_to 'Edit', edit_automovel_path(@automovel) %> |
<%= link_to 'Back', automovels_path %>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :seguro %><br />
    <%= f.text_field :seguro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Cpf</th>
    <th>Rg</th>
    <th>Endereco</th>
    <th>Seguro</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.telefone %></td>
    <td><%= cliente.cpf %></td>
    <td><%= cliente.rg %></td>
    <td><%= cliente.endereco %></td>
    <td><%= cliente.seguro %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @cliente.telefone %>
</p>

<p>
  <b>Cpf:</b>
  <%= @cliente.cpf %>
</p>

<p>
  <b>Rg:</b>
  <%= @cliente.rg %>
</p>

<p>
  <b>Endereco:</b>
  <%= @cliente.endereco %>
</p>

<p>
  <b>Seguro:</b>
  <%= @cliente.seguro %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Associacao</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ocorrencia/_form.html.haml
= semantic_form_for(@ocorrencium) do |f|
  = f.input :codigo, :label => 'codigo'
  = f.input :data, :label => 'data'
  = f.input :descricao, :label => 'descricao'
  = f.input :hora, :label => 'hora'
  = f.input :cliente, :member_label => :nome, :label => 'cliente'
  = f.input :seguro, :member_label => :tipo, :label => 'seguro'
  = f.input :automovel, :member_label => :marca, :label => 'automovel'
  = f.submit 'Salvar'
  

app/views/ocorrencia/edit.html.erb
<h1>Editing ocorrencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @ocorrencium %> |
<%= link_to 'Back', ocorrencia_path %>

app/views/ocorrencia/index.html.erb
<h1>Listing ocorrencia</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Data</th>
    <th>Descricao</th>
    <th>Hora</th>
    <th>Cliente</th>
    <th>Seguro</th>
    <th>Automovel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ocorrencia.each do |ocorrencium| %>
  <tr>
    <td><%= ocorrencium.codigo %></td>
    <td><%= ocorrencium.data %></td>
    <td><%= ocorrencium.descricao %></td>
    <td><%= ocorrencium.hora %></td>
    <td><%= ocorrencium.cliente %></td>
    <td><%= ocorrencium.seguro %></td>
    <td><%= ocorrencium.automovel %></td>
    <td><%= link_to 'Show', ocorrencium %></td>
    <td><%= link_to 'Edit', edit_ocorrencium_path(ocorrencium) %></td>
    <td><%= link_to 'Excluir', ocorrencium, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ocorrencium', new_ocorrencium_path %>

app/views/ocorrencia/new.html.erb
<h1>New ocorrencium</h1>

<%= render 'form' %>

<%= link_to 'Back', ocorrencia_path %>

app/views/ocorrencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @ocorrencium.codigo %>
</p>

<p>
  <b>Data:</b>
  <%= @ocorrencium.data %>
</p>

<p>
  <b>Descricao:</b>
  <%= @ocorrencium.descricao %>
</p>

<p>
  <b>Hora:</b>
  <%= @ocorrencium.hora %>
</p>

<p>
  <b>Cliente:</b>
  <%= @ocorrencium.cliente.nome %>
</p>

<p>
  <b>Seguro:</b>
  <%= @ocorrencium.seguro.tipo %>
</p>

<p>
  <b>Automovel:</b>
  <%= @ocorrencium.automovel.marca %>
</p>


<%= link_to 'Edit', edit_ocorrencium_path(@ocorrencium) %> |
<%= link_to 'Back', ocorrencia_path %>

app/views/seguros/_form.html.haml
= semantic_form_for(@seguro) do |f|
	= f.input :codigo, :label => 'codigo'
	= f.input :tipo, :label => 'tipo'
	= f.input :descricao, :label => 'descricao'
	= f.input :automovel, :member_label => :marca, :label => 'automovel'
	= f.submit 'Salvar'
  

app/views/seguros/edit.html.erb
<h1>Editing seguro</h1>

<%= render 'form' %>

<%= link_to 'Show', @seguro %> |
<%= link_to 'Back', seguros_path %>

app/views/seguros/index.html.erb
<h1>Listing seguros</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Tipo</th>
    <th>Descricao</th>
    <th>Automovel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seguros.each do |seguro| %>
  <tr>
    <td><%= seguro.codigo %></td>
    <td><%= seguro.tipo %></td>
    <td><%= seguro.descricao %></td>
    <td><%= seguro.automovel %></td>
    <td><%= link_to 'Show', seguro %></td>
    <td><%= link_to 'Edit', edit_seguro_path(seguro) %></td>
    <td><%= link_to 'Excluir', seguro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seguro', new_seguro_path %>

app/views/seguros/new.html.erb
<h1>New seguro</h1>

<%= render 'form' %>

<%= link_to 'Back', seguros_path %>

app/views/seguros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @seguro.codigo %>
</p>

<p>
  <b>Tipo:</b>
  <%= @seguro.tipo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @seguro.descricao %>
</p>

<p>
  <b>Automovel:</b>
  <%= @seguro.automovel.marca %>
</p>


<%= link_to 'Edit', edit_seguro_path(@seguro) %> |
<%= link_to 'Back', seguros_path %>